routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@beranda')->name('beranda');


Route::get('/all_loker', 'FrontendController@showAllLoker')->name('show.all'); 
Route::get('/cari_loker', 'FrontendController@cariLoker')->name('cari.loker');
Route::get('/show_loker/{loker}', 'FrontendController@showLoker')->name('show.loker');
Route::get('/kategori/{category}', 'FrontendController@categoryLoker')->name('category.loker');


Auth::routes();



Route::middleware('auth')->group(function(){

//auth frontend
Route::get('/home', 'HomeController@index')->name('home');
Route::delete('/message/hapus/{message}', 'HomeController@destroyPesan')->name('message.hapus');
Route::delete('/post/hapus/{post}', 'HomeController@destroyPost')->name('post.hapus');
Route::resource('/chatroom', 'ChatRoomController');
Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
Route::get('/comment/{post}', 'CommentController@index');

Route::PATCH('/profil/update/{id}', 'FrontendController@updateProfil')->name('updateProfil');

Route::PATCH('/kirim_pesan', 'FrontendController@kirimMessage')->name('kirim.message');
Route::get('/registerGraduate', 'FrontendController@registerGraduate')->name('registerGraduate');
Route::get('/pilihGraduate/{pilih}', 'FrontendController@pilihGraduate')->name('pilihGraduate');

//kuliah
Route::get('/profil/{graduate}/kuliah', 'FrontendController@ketKuliah')->name('ket.kuliah');
Route::PATCH('/profil/kuliah/{graduate}', 'FrontendController@profilKuliah')->name('profil.kuliah');
Route::PATCH('/profil-kuliah/update/{study}', 'FrontendController@updateProfilKuliah')->name('updateProfil.kuliah');
//wirausaha
Route::get('/profil/{graduate}/wirausaha', 'FrontendController@ketWirausaha')->name('ket.wirausaha');
Route::PATCH('/profil/wirausaha/{graduate}', 'FrontendController@profilWirausaha')->name('profil.wirausaha');
Route::PATCH('/profil-wirausaha/update/{business}', 'FrontendController@updateProfilWirausaha')->name('updateProfil.wirausaha');
//bekerja
Route::get('/profil/{graduate}/bekerja', 'FrontendController@ketBekerja')->name('ket.bekerja');
Route::PATCH('/profil/bekerja/{graduate}', 'FrontendController@profilBekerja')->name('profil.bekerja');
Route::PATCH('/profil-bekerja/update/{work}', 'FrontendController@updateProfilBekerja')->name('updateProfil.bekerja');

//auth admin
Route::resource('/admin', 'AdminController');
Route::resource('/manajemen_alumni', 'ManajemenAlumniController');
Route::resource('/akun', 'AkunController');
Route::get('/akun/{user}/hapusgraduate', 'AkunController@hapusGraduate')->name('hapus.graduate');

//keterangan alumni kuliah
Route::get('/graduate/{graduate}/kuliah', 'KeteranganController@pilihKuliah')->name('pilih.kuliah');
Route::PATCH('/graduate/kuliah/{graduate}', 'KeteranganController@kuliah')->name('kuliah');
Route::get('/kuliah/{graduate}/edit', 'KeteranganController@editKuliah')->name('edit.kuliah');
Route::PATCH('/kuliah/update/{study}', 'KeteranganController@updateKuliah')->name('update.kuliah');

//keterangan alumni wirausaha
Route::get('/graduate/{graduate}/wirausaha', 'KeteranganController@pilihWirausaha')->name('pilih.wirausaha');
Route::PATCH('/graduate/wirausaha/{graduate}', 'KeteranganController@wirausaha')->name('wirausaha');
Route::get('/wirausaha/{graduate}/edit', 'KeteranganController@editWirausaha')->name('edit.wirausaha');
Route::PATCH('/wirausaha/update/{business}', 'KeteranganController@updateWirausaha')->name('update.wirausaha');

//keterangan alumni bekerja
Route::get('/graduate/{graduate}/bekerja', 'KeteranganController@pilihBekerja')->name('pilih.bekerja');
Route::PATCH('/graduate/bekerja/{graduate}', 'KeteranganController@bekerja')->name('bekerja');
Route::get('/bekerja/{graduate}/edit', 'KeteranganController@editBekerja')->name('edit.bekerja');
Route::PATCH('/bekerja/update/{work}', 'KeteranganController@updateBekerja')->name('update.bekerja');

Route::get('/Graduate/export_excel', 'ExportImportController@export_excel')->name('graduate.export');
Route::post('/Graduate/import_excel', 'ExportImportController@import_excel')->name('graduate.import');
Route::resource('/bursa_kerja', 'BursaKerjaController');
Route::resource('/category', 'CategoryController');
Route::resource('/mou', 'MouController');
//manajemen website
Route::get('/manajemen_website', 'WebsiteController@index')->name('manajemen.website');
Route::PATCH('/manajemen_website/update/', 'WebsiteController@update')->name('update.website');

});


// Route::get('/graduate/login', 'GraduateLoginController@showLoginForm')->name('graduate.loginform');
// Route::get('/graduate/register', 'GraduateLoginController@showRegisterForm')->name('graduate.registerform');
// Route::post('/graduate/login', 'GraduateLoginController@login')->name('graduate.login');
// Route::post('/graduate/register', 'GraduateLoginController@register')->name('graduate.register');
// Route::get('/graduate/profil', 'GraduateLoginController@index')->middleware('auth:graduate')->name('profil.alumni');
// Route::get('/graduate/logout', 'GraduateLoginController@logout')->name('graduate.logout');


// Route::PATCH('/profil/kuliah/{auth}', 'KeteranganController@kuliah')->name('submit.kuliah');

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Auth;
use App\Website;
use App\Loker;
use App\Category;
use App\Message;
use App\Mou;
use App\Graduate;
use App\Study;
use App\Business;
use App\Work;
use App\Income;
use App\Status;
use App\Location;
use App\User;
use File;

class FrontendController extends Controller
{
    public function beranda()
    {
        $website = Website::first();

        $jmlhloker = Loker::count();
        $jmlhgraduate = Graduate::count();
        $jmlhmou = Mou::count();

        if ($jmlhloker >= 6) {
            $lokers = Loker::orderBy('id','DESC')->paginate(6);
        }else {
            $lokers = Loker::orderBy('id','DESC')->paginate(3);
        }
        
        $mous = Mou::all();
        $categories = Category::all();
        return view('frontend.beranda', compact('website', 'lokers', 'mous', 'jmlhloker', 'jmlhgraduate', 'jmlhmou', 'categories'));
    }

    public function showAllLoker()
    {
        $website = Website::first();
        $lokers = Loker::orderBy('id','DESC')->paginate(3);
        $newlokers = Loker::orderBy('id','DESC')->paginate(5);
        $categories = Category::all();
        return view('frontend.loker_all', compact('website', 'lokers', 'newlokers', 'categories'));
    }

    public function cariLoker(Request $request)
	{
		$website = Website::first();

        // menangkap data pencarian
		$cari = $request->cari;
 
    		// mengambil data dari table pegawai sesuai pencarian data
		$lokers = Loker::where('title','like',"%".$cari."%")
		->paginate(3);
        $newlokers = Loker::orderBy('id','DESC')->paginate(5);
        $categories = Category::all();
 
    		// mengirim data pegawai ke view index
		return view('frontend.loker_all', compact('website', 'lokers', 'newlokers', 'categories'));
 
	}

    public function showLoker($id)
    {
        $website = Website::first();
        $categories = Category::all();
        $loker = Loker::find($id);
        return view('frontend.show_loker', compact('website', 'loker', 'categories'));
    }

    public function categoryLoker($id)
    {
        $website = Website::first();
        
        $newlokers = Loker::orderBy('id','DESC')->paginate(5);
        $categories = Category::all();
        $lokers = Loker::where('category_id',$id)
        ->orderBy('id','DESC')->paginate(3);
        return view('frontend.loker_all', compact('website', 'lokers', 'newlokers', 'categories'));
    }

    public function kirimMessage(Request $request)
    {
        $message = new Message;
            $message->name = $request->name;
            $message->email = $request->email;
            $message->subject = $request->subject;
            $message->pesan = $request->pesan;
            $message->save(); 

        return redirect('/home')->with('success', 'Pesan anda telah terkirim!');
    }

    public function registerGraduate(){
        
        $website = Website::first();
        $id = Auth::id();
        $statuses = Status::all();
        $incomes = Income::all();
        $locations = Location::all();
        $categories = Category::all();
        $graduate = Graduate::where('id', $id)->first();
        $study = Study::where('graduate_id', $id)->first();
        $business = Business::where('graduate_id', $id)->first();
        $work = Work::where('graduate_id', $id)->first();
        return view('frontend.auth.registerGraduate', compact('website','graduate', 'study', 'business', 'work', 'statuses', 'incomes', 'locations', 'categories'));
        
    }

    public function pilihGraduate($id)
    {
        $iduser = Auth::id();
        $website = Website::first();
        $categories = Category::all();
        $alumni = Graduate::find($id);
            $alumni->user_id = $iduser; 
            $alumni->push();
        $graduate = Graduate::where('user_id', $iduser)->first();
        return back();
    }

    //status kuliah
    public function ketKuliah($id)
    {
        $website = Website::first();
        $categories = Category::all();
        $graduate = Graduate::find($id);
        $statuses = Status::all();
        return view('frontend.keterangan.ketKuliah', compact('website', 'categories', 'graduate', 'statuses'));
    }

    public function profilKuliah(Request $request, $id)
    {
        
        // dd($request->all());
        $graduate = Graduate::find($id);
        // dd($graduate->id);
        $business = Business::where('graduate_id', $graduate->id)->get();
        $work = Work::where('graduate_id', $graduate->id)->get();

        if (!$business->isEmpty()) {

            $graduate->keterangan = "kuliah";
            $graduate->push();
            $id_alumni = $graduate->id;
            $study = new Study;
                $study->nma_prgu = $request->nma_prgu;
                $study->jurusan = $request->jurusan;
                $study->mulai = $request->mulai;
                $study->status_id = $request->status_id;
                $study->graduate_id = $id_alumni;
                $study->save(); 

                $business = Business::where('graduate_id', $graduate->id)->first();
                $business->delete();

            return redirect('/home')->with('success', 'Status wirausaha dihapus dan status kuliah telah ditambahkan');

        }elseif (!$work->isEmpty()) {
             
            $graduate->keterangan = "kuliah";
            $graduate->push();
            $id_alumni = $graduate->id;
            $study = new Study;
                $study->nma_prgu = $request->nma_prgu;
                $study->jurusan = $request->jurusan;
                $study->mulai = $request->mulai;
                $study->status_id = $request->status_id;
                $study->graduate_id = $id_alumni;
                $study->save(); 

                $work = work::where('graduate_id', $graduate->id)->first();
                $work->delete();
            
            return redirect('/home')->with('success', 'Status bekerja dihapus dan status kuliah telah ditambahkan');

        }else {
            $graduate->keterangan = "kuliah";
            $graduate->push();
            $id_alumni = $graduate->id;
            $study = new Study;
                $study->nma_prgu = $request->nma_prgu;
                $study->jurusan = $request->jurusan;
                $study->mulai = $request->mulai;
                $study->status_id = $request->status_id;
                $study->graduate_id = $id_alumni;
                $study->save(); 

            return redirect('/home')->with('success', 'Status kuliah telah ditambahkan');
        }
        
    }

    public function updateProfilKuliah(Request $request, $id)
    {
        // dd($request->all());
        $study = Study::find($id);
        $study->nma_prgu = $request->nma_prgu;
        $study->jurusan = $request->jurusan;
        $study->mulai = $request->mulai;
        $study->status_id = $request->status_id;
        $study->push(); 

        return redirect('/home')->with('success', 'Status kuliah telah diperbaharui');
    }

    //status wirausaha
    public function ketWirausaha($id)
    {
        $website = Website::first();
        $categories = Category::all();
        $graduate = Graduate::find($id);
        $incomes = Income::all();
        $statuses = Status::all();
        return view('frontend.keterangan.ketWirausaha', compact('website', 'categories', 'graduate', 'statuses', 'incomes'));
    }

    public function profilWirausaha(Request $request, $id)
    {
        
        // dd($request->all());
        $graduate = Graduate::find($id);
        $study = Study::where('graduate_id', $graduate->id)->get();
        $work = Work::where('graduate_id', $graduate->id)->get();
        if (!$study->isEmpty()) {
            
            $graduate->keterangan = "wirausaha";
            $graduate->push();
            $id_alumni = $graduate->id;
            $business = new Business;
                $business->nma_pru = $request->nma_pru;
                $business->jenis = $request->jenis;
                $business->mulai = $request->mulai;
                $business->status_id = $request->status_id;
                $business->income_id = $request->income_id;
                $business->graduate_id = $id_alumni;
                $business->save(); 

                $study = Study::where('graduate_id', $graduate->id)->first();
                $study->delete();
    
            return redirect('/home')->with('success', 'Status kuliah dihapus dan status wirausaha telah ditambahkan');

        }elseif (!$work->isEmpty()) {
             
            $graduate->keterangan = "wirausaha";
            $graduate->push();
            $id_alumni = $graduate->id;
            $business = new Business;
                $business->nma_pru = $request->nma_pru;
                $business->jenis = $request->jenis;
                $business->mulai = $request->mulai;
                $business->status_id = $request->status_id;
                $business->income_id = $request->income_id;
                $business->graduate_id = $id_alumni;
                $business->save(); 

                $work = Work::where('graduate_id', $graduate->id)->first();
                $work->delete();
    
            return redirect('/home')->with('success', 'Status bekerja dihapus dan status wirausaha telah ditambahkan');

        }else {

            $graduate->keterangan = "wirausaha";
            $graduate->push();
            $id_alumni = $graduate->id;
            $business = new Business;
                $business->nma_pru = $request->nma_pru;
                $business->jenis = $request->jenis;
                $business->mulai = $request->mulai;
                $business->status_id = $request->status_id;
                $business->income_id = $request->income_id;
                $business->graduate_id = $id_alumni;
                $business->save(); 
    
            return redirect('/home')->with('success', 'Status wirausaha telah ditambahkan');

resources/views/frontend/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <!-- <meta name="csrf-token" content="{{ csrf_token() }}"> -->

  <title>Bursa Kerja Khusus (BKK) SMKN 1 Tebas</title>
  <meta content="" name="description">

  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ asset('images/'.$website->header_logo) }}" rel="icon">
  <link href="{{ asset('images/'.$website->header_logo) }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ asset('assets_frontend/assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets_frontend/assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ asset('assets_frontend/assets/vendor/aos/aos.css') }}" rel="stylesheet">
  <link href="{{ asset('assets_frontend/assets/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ asset('assets_frontend/assets/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">
  <link href="{{ asset('assets_frontend/assets/vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ asset('assets_frontend/assets/css/style.css') }}" rel="stylesheet">
  <!-- Custom CSS -->
  <!-- <link href="{{ asset('/assets_backend/css/style.min.css') }}" rel="stylesheet"> -->
  
  
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.css"/>
  <!-- <link rel="stylesheet" type="text/css" href="{{ asset('/assets_backend/vendor/datatables/datatables.min.css') }}"/> -->
  <!-- <link rel="stylesheet" href="{{ asset('/assets_backend/bootstrap452/bootstrap.min.css') }}"> -->

  <!-- =======================================================
  * Template Name: FlexStart - v1.2.0
  * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <img src="{{ asset('images/'.$website->header_logo) }}" alt="">
        <h5 class="mt-2"><strong>{{ $website->header_title }}</strong></h5>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto" href="/.#hero">Beranda</a></li>
          <!-- <li><a class="nav-link scrollto" href="#services">Services</a></li> -->
          <li><a class="nav-link scrollto" href="/.#about">Tentang</a></li>
          <li><a class="nav-link scrollto" href="/.#recent-blog-posts">Loker</a></li>
          <!-- <li><a class="nav-link scrollto" href="/.#contact">Kontak</a></li> -->
          <li><a href="{{ route('show.all') }}">Cari</a></li>
          @guest
              <li><a class="nav-link" href="{{ route('login') }}">Login</a></li>
              @if (Route::has('register'))
                  <li><a class="nav-link" href="{{ route('register') }}">Register</a></li>
              @endif
          @else 
              @if(Auth::user()->status == "2")
              <li><a href="{{ route('chatroom.index') }}">{{ __('Postingan') }}</a></li>
              <li class="dropdown"><a href="#"><span>Home</span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                  <li><a href="{{ url('/home') }}">Profil</a></li>
                  <li><a class="dropdown-item" href="{{ route('logout') }}"
                          onclick="event.preventDefault();
                                          document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                </ul>
              </li>
              @elseif(Auth::user()->status == "1")
              <li><a href="{{ url('/home') }}"><i class="bi bi-door-open-fill" style="font-size: 1.5em;"></i></a></li>
              @endif
          @endguest

          <!-- <li><a class="getstarted scrollto" href="#about">Get Started</a></li> -->
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

    @yield('content')
  
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <!-- <div class="col-lg-12 text-center">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div> -->
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="/" class="logo d-flex align-items-center">
              <img src="{{ asset('images/logobkk.png') }}" alt="">
              <span>BKK SMKN 1 Tebas</span>
            </a>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="{{ $website->footer_twitter }}" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="{{ $website->footer_facebook }}" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="{{ $website->footer_instagram }}" class="instagram"><i class="bi bi-instagram bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin bx bxl-linkedin"></i></a>
              <a href="{{ $website->footer_youtube }}" class="youtube"><i class="bi bi-youtube"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Menu Utama</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="/.#hero">Beranda</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="/.#about">Tentang</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="/.#recent-blog-posts">Loker</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="/.#contact">Kontak</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="{{ route('show.all') }}">Cari Loker</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Kategori Loker</h4>
            <ul>

              @foreach( $categories as $category )
              <li><i class="bi bi-chevron-right"></i> <a href="{{ route('category.loker', $category) }}">{{ $category->kategori }} <span>({{ $category->loker->count() }})</span></a></li>
              @endforeach

              <!-- <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li> -->
              
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>{{ $website->contact_alamat }}
              <!-- Jalan H. Said, Dsn. Melati<br>
              Ds. Tebas Sungai, Kec. Tebas<br>
              Kab. Sambas Kalimantan Barat<br>
              Kode Pos 79461 <br>
              Indonesia <br> -->
              <strong>Phone:</strong> (0562) 371-221 / (0562) 392-708<br>
              <strong>Email:</strong> smkn01tebas@gmail.com<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>BKK SMKN 1 Tebas</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  
  <!-- script vue.js -->
  <script src="{{ asset('js/app.js') }}"></script>

  <!-- Vendor JS Files -->
  <script src="{{ asset('assets_frontend/assets/vendor/bootstrap/js/bootstrap.bundle.js') }}"></script>
  <script src="{{ asset('assets_frontend/assets/vendor/aos/aos.js') }}"></script>
  <script src="{{ asset('assets_frontend/assets/vendor/php-email-form/validate.js') }}"></script>
  <script src="{{ asset('assets_frontend/assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
  <script src="{{ asset('assets_frontend/assets/vendor/purecounter/purecounter.js') }}"></script>
  <script src="{{ asset('assets_frontend/assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ asset('assets_frontend/assets/vendor/glightbox/js/glightbox.min.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ asset('assets_frontend/assets/js/main.js') }}"></script>
  
  <script src="{{ asset('/assets_backend/assets/plugins/jquery/dist/jquery.min.js') }}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <!-- <script type="text/javascript" src="{{ asset('assets_backend/vendor/datatables/datatables.min.js') }}"></script> -->

    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.js"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
    $('#example-ok').DataTable();
    } );
    </script>

</body>

</html>