routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@beranda')->name('beranda');


Route::get('/all_loker', 'FrontendController@showAllLoker')->name('show.all'); 
Route::get('/cari_loker', 'FrontendController@cariLoker')->name('cari.loker');
Route::get('/show_loker/{loker}', 'FrontendController@showLoker')->name('show.loker');
Route::get('/kategori/{category}', 'FrontendController@categoryLoker')->name('category.loker');


Auth::routes();



Route::middleware('auth')->group(function(){

//auth frontend
Route::get('/home', 'HomeController@index')->name('home');
Route::delete('/message/hapus/{message}', 'HomeController@destroyPesan')->name('message.hapus');
Route::delete('/post/hapus/{post}', 'HomeController@destroyPost')->name('post.hapus');
Route::resource('/chatroom', 'ChatRoomController');
Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
Route::get('/comment/{post}', 'CommentController@index');

Route::PATCH('/profil/update/{id}', 'FrontendController@updateProfil')->name('updateProfil');

Route::PATCH('/kirim_pesan', 'FrontendController@kirimMessage')->name('kirim.message');
Route::get('/registerGraduate', 'FrontendController@registerGraduate')->name('registerGraduate');
Route::get('/pilihGraduate/{pilih}', 'FrontendController@pilihGraduate')->name('pilihGraduate');

//kuliah
Route::get('/profil/{graduate}/kuliah', 'FrontendController@ketKuliah')->name('ket.kuliah');
Route::PATCH('/profil/kuliah/{graduate}', 'FrontendController@profilKuliah')->name('profil.kuliah');
Route::PATCH('/profil-kuliah/update/{study}', 'FrontendController@updateProfilKuliah')->name('updateProfil.kuliah');
//wirausaha
Route::get('/profil/{graduate}/wirausaha', 'FrontendController@ketWirausaha')->name('ket.wirausaha');
Route::PATCH('/profil/wirausaha/{graduate}', 'FrontendController@profilWirausaha')->name('profil.wirausaha');
Route::PATCH('/profil-wirausaha/update/{business}', 'FrontendController@updateProfilWirausaha')->name('updateProfil.wirausaha');
//bekerja
Route::get('/profil/{graduate}/bekerja', 'FrontendController@ketBekerja')->name('ket.bekerja');
Route::PATCH('/profil/bekerja/{graduate}', 'FrontendController@profilBekerja')->name('profil.bekerja');
Route::PATCH('/profil-bekerja/update/{work}', 'FrontendController@updateProfilBekerja')->name('updateProfil.bekerja');

//auth admin
Route::resource('/admin', 'AdminController');
Route::resource('/manajemen_alumni', 'ManajemenAlumniController');
Route::resource('/akun', 'AkunController');
Route::get('/akun/{user}/hapusgraduate', 'AkunController@hapusGraduate')->name('hapus.graduate');

//keterangan alumni kuliah
Route::get('/graduate/{graduate}/kuliah', 'KeteranganController@pilihKuliah')->name('pilih.kuliah');
Route::PATCH('/graduate/kuliah/{graduate}', 'KeteranganController@kuliah')->name('kuliah');
Route::get('/kuliah/{graduate}/edit', 'KeteranganController@editKuliah')->name('edit.kuliah');
Route::PATCH('/kuliah/update/{study}', 'KeteranganController@updateKuliah')->name('update.kuliah');

//keterangan alumni wirausaha
Route::get('/graduate/{graduate}/wirausaha', 'KeteranganController@pilihWirausaha')->name('pilih.wirausaha');
Route::PATCH('/graduate/wirausaha/{graduate}', 'KeteranganController@wirausaha')->name('wirausaha');
Route::get('/wirausaha/{graduate}/edit', 'KeteranganController@editWirausaha')->name('edit.wirausaha');
Route::PATCH('/wirausaha/update/{business}', 'KeteranganController@updateWirausaha')->name('update.wirausaha');

//keterangan alumni bekerja
Route::get('/graduate/{graduate}/bekerja', 'KeteranganController@pilihBekerja')->name('pilih.bekerja');
Route::PATCH('/graduate/bekerja/{graduate}', 'KeteranganController@bekerja')->name('bekerja');
Route::get('/bekerja/{graduate}/edit', 'KeteranganController@editBekerja')->name('edit.bekerja');
Route::PATCH('/bekerja/update/{work}', 'KeteranganController@updateBekerja')->name('update.bekerja');

Route::get('/Graduate/export_excel', 'ExportImportController@export_excel')->name('graduate.export');
Route::post('/Graduate/import_excel', 'ExportImportController@import_excel')->name('graduate.import');
Route::resource('/bursa_kerja', 'BursaKerjaController');
Route::resource('/category', 'CategoryController');
Route::resource('/mou', 'MouController');
//manajemen website
Route::get('/manajemen_website', 'WebsiteController@index')->name('manajemen.website');
Route::PATCH('/manajemen_website/update/', 'WebsiteController@update')->name('update.website');

});


// Route::get('/graduate/login', 'GraduateLoginController@showLoginForm')->name('graduate.loginform');
// Route::get('/graduate/register', 'GraduateLoginController@showRegisterForm')->name('graduate.registerform');
// Route::post('/graduate/login', 'GraduateLoginController@login')->name('graduate.login');
// Route::post('/graduate/register', 'GraduateLoginController@register')->name('graduate.register');
// Route::get('/graduate/profil', 'GraduateLoginController@index')->middleware('auth:graduate')->name('profil.alumni');
// Route::get('/graduate/logout', 'GraduateLoginController@logout')->name('graduate.logout');


// Route::PATCH('/profil/kuliah/{auth}', 'KeteranganController@kuliah')->name('submit.kuliah');

app/Http/Controllers/AkunController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\User;
use App\Graduate;
use App\Website;

class AkunController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $website = Website::first();
        $users = User::where('status', "2")->get();
        return view('backend.akun.index', compact('website', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User;
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->status = "2";
            $user->save(); 

        return redirect()->route('akun.index')->with('success', 'Data telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $graduate = Graduate::where('user_id', $id)->first();
        // $graduate->user_id = "";
        // $graduate->push();

        // $users = User::where('status', "2")->get();
        // return view('backend.akun.index', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $website = Website::first();
        $user = User::find($id);
        // $graduate = Graduate::where('user_id', $id)->first();
        return view('backend.akun.edit', compact('website', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->password == null)
        {
            $user = User::find($id);
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = $user->password; 
            $user->push(); 
        }else
        {
            $user = User::find($id);
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->push(); 
        }

        return redirect()->route('akun.index')->with('update', 'Data telah diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('akun.index')->with('delete', 'Data telah dihapus');
    }

    public function hapusGraduate($id)
    {
        $graduate = Graduate::where('user_id', $id)->firstOrFail();
        $graduate->user_id = null;
        $graduate->push();

        $users = User::where('status', "2")->get();
        return view('backend.akun.index', compact('users'));
    }
}

resources/views/backend/akun/edit.blade.php
@extends('backend.layouts.main')

@section('content')
<div class="page-wrapper mt-5 pt-4">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row align-items-center">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="page-title mb-0 p-0">Edit Akun</h3>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit Akun</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-md-6 col-4 align-self-center">
                <div class="text-end upgrade-btn">
                    <!-- Button trigger modal -->
                    <!-- <button type="button" class="btn btn-success d-md-inline-block text-white" data-toggle="modal" data-target="#tambahBursa">
                        Tambah
                    </button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-4 col-xlg-3 col-md-5">
                <div class="card">
                    <div class="bg-info text-white card-header">
                       <strong>Data Akun</strong> 
                    </div>
                    <div class="card-body profile-card">
                        <center class="mt-4"> <img src="{{ asset('/profil/'.Auth::user()->profil) }}"
                                class="rounded-circle" width="150" />
                            <!-- <h4 class="card-title mt-2">{{ $user->name }}</h4>
                            <h6 class="card-subtitle">Gmail : {{ $user->email }}</h6>
                            <div class="row justify-content-center">
                                <div class="col-4">
                                    <a href="javascript:void(0)" class="link">
                                        <i class="icon-people" aria-hidden="true"></i>
                                        <span class="font-normal">254</span>
                                    </a></div>
                                <div class="col-4">
                                    <a href="javascript:void(0)" class="link">
                                        <i class="icon-picture" aria-hidden="true"></i>
                                        <span class="font-normal">54</span>
                                    </a></div>
                            </div>  -->
                            <hr>
                        </center>
                        <form  method="post" action="{{ route('akun.update', $user) }}" class="form-horizontal form-material mx-2">
                        @csrf
                        @method('PATCH')
                            <div class="form-group">
                                <label class="col-md-12 mb-0">Nama</label>
                                <div class="col-md-12">
                                    <input type="text" name="name" value="{{ $user->name }}" required
                                        class="form-control ps-0 form-control-line">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="example-email" class="col-md-12">Email</label>
                                <div class="col-md-12">
                                    <input type="email" name="email" value="{{ $user->email }}" required
                                        class="form-control ps-0 form-control-line">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 mb-0">Password</label>
                                <div class="col-md-12">
                                    <input type="password" name="password" placeholder="..........."
                                        class="form-control ps-0 form-control-line">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12 text-right">
                                    <button type="submit" class="btn btn-success mx-auto mx-md-0 text-white">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-lg-8 col-xlg-9 col-md-7">
                <div class="card">
                    <div class="bg-info text-white card-header">
                       <strong>Data Alumni</strong> 
                    </div>
                    @isset($user->graduate->name)
                    <div class="card-body">
                        <form class="form-horizontal form-material mx-2">
                            <div class="form-group">
                                <label class="col-md-12 mb-0">Nama</label>
                                <div class="col-md-12">
                                    <input value="{{ $user->graduate->name }}"
                                        class="form-control ps-0 form-control-line" readonly>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="example-email" class="col-md-12">NISN</label>
                                <div class="col-md-12">
                                    <input value="{{ $user->graduate->nisn }}"
                                        class="form-control ps-0 form-control-line" readonly>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 mb-0">Tahun Lulus</label>
                                <div class="col-md-12">
                                    <input value="{{ $user->graduate->th_lulus }}"
                                        class="form-control ps-0 form-control-line" readonly>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 mb-0">Jurusan</label>
                                <div class="col-md-12">
                                    <input value="{{ $user->graduate->department }}"
                                        class="form-control ps-0 form-control-line" readonly>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12 mb-0">Keterangan</label>
                                <div class="col-md-12">
                                    <input value="{{ $user->graduate->keterangan }}"
                                        class="form-control ps-0 form-control-line" readonly>
                                </div>
                            </div>
                        </form>
                        <div class="form-group">
                            <div class="col-sm-12 text-right">
                                <a href="{{ route('hapus.graduate', $user->id) }}" class="btn btn-warning mx-auto mx-md-0 text-white">Hapus</a>
                            </div>
                        </div>
                    </div>
                    @endisset
                    @empty($user->graduate->name)
                    <div class="card-body text-center">
                        <h3><i>Akun ini tidak memiliki data alumni yang dipilih</i></h3>
                    </div>
                    @endempty
                </div>
            </div>
            <!-- Column -->
        </div>
        <!-- Row -->
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        © 2021 Bursa Kerja Khusus by <a href="https://smkn1tebas.sch.id/">smkn1tebas.sch.id</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>


@endsection

  

resources/views/backend/akun/index.blade.php
@extends('backend.layouts.main')

@section('content')
<div class="page-wrapper mt-5 pt-4">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
    @if(Session::has('success'))
        <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ Session::get('success') }}</strong>
        </div>
    @endif
    @if(Session::has('update'))
        <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ Session::get('update') }}</strong>
        </div>
    @endif
    @if(Session::has('delete'))
        <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ Session::get('delete') }}</strong>
        </div>
    @endif
        <div class="row align-items-center">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="page-title mb-0 p-0">Manajemen Akun</h3>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Manajemen Akun</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-md-6 col-4 align-self-center">
                <div class="text-end upgrade-btn">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-success d-md-inline-block text-white" data-toggle="modal" data-target="#tambahBursa">
                        Tambah
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <!-- <h4 class="card-title">Basic Table</h4>
                        <h6 class="card-subtitle">Add class <code>.table</code></h6> -->
                        <div class="table-responsive">
                            <table class="table user-table table-bordered" id="example-ok">
                                <thead>
                                    <tr>
                                        <!-- <th class="border-top-0">#</th> -->
                                        <th class="border-top-0">Nama</th>
                                        <th class="border-top-0">Email</th>
                                        <th class="border-top-0">Nama Alumni</th>
                                        <th class="border-top-0">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <!-- @php $i=1 @endphp -->
                                    @foreach($users as $user)
                                    <tr>
                                        <!-- <td>{{ $i++ }}</td> -->
                                        <td><span class="round"><img src="{{ asset('/profil/'.$user->profil) }}"
                                                    alt="user" width="50"></span> {{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        @if(isset($user->graduate->name))
                                        <td>
                                        {{ $user->graduate->name }}
                                        </td>
                                        @else
                                        <td>null</td>
                                        @endif
                                        <td>
                                            <form action="{{ route('akun.destroy', $user) }}" method="post">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <a class="btn btn-success" href="{{ route('akun.edit', $user) }}"><i class="fa fa-edit fa-fw"></i></a>
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Yakin ingin menghapus data?')"><i class="fa fa-trash fa-fw"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        © 2021 Bursa Kerja Khusus by <a href="https://smkn1tebas.sch.id/">smkn1tebas.sch.id</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>

<!-- Modal Tambah Alumni-->
<div class="modal fade" id="tambahBursa" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-secondary text-white">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Admin Baru</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post" action="{{ route('akun.store') }}">
        @csrf
        <div class="modal-body">

          
              <div class="form-group">
                <label for="exampleInputNama">Nama</label>
                <input type="text" name="name" class="form-control" id="exampleInputNama"  required>
                <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Email</label>
                <input type="text" name="email" class="form-control" id="exampleInputNama"  required>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputNama" required>
              </div>
            
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
          <button type="Submit" class="btn btn-info">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>

@endsection