routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@beranda')->name('beranda');


Route::get('/all_loker', 'FrontendController@showAllLoker')->name('show.all'); 
Route::get('/cari_loker', 'FrontendController@cariLoker')->name('cari.loker');
Route::get('/show_loker/{loker}', 'FrontendController@showLoker')->name('show.loker');
Route::get('/kategori/{category}', 'FrontendController@categoryLoker')->name('category.loker');


Auth::routes();



Route::middleware('auth')->group(function(){

//auth frontend
Route::get('/home', 'HomeController@index')->name('home');
Route::delete('/message/hapus/{message}', 'HomeController@destroyPesan')->name('message.hapus');
Route::delete('/post/hapus/{post}', 'HomeController@destroyPost')->name('post.hapus');
Route::resource('/chatroom', 'ChatRoomController');
Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
Route::get('/comment/{post}', 'CommentController@index');

Route::PATCH('/profil/update/{id}', 'FrontendController@updateProfil')->name('updateProfil');

Route::PATCH('/kirim_pesan', 'FrontendController@kirimMessage')->name('kirim.message');
Route::get('/registerGraduate', 'FrontendController@registerGraduate')->name('registerGraduate');
Route::get('/pilihGraduate/{pilih}', 'FrontendController@pilihGraduate')->name('pilihGraduate');

//kuliah
Route::get('/profil/{graduate}/kuliah', 'FrontendController@ketKuliah')->name('ket.kuliah');
Route::PATCH('/profil/kuliah/{graduate}', 'FrontendController@profilKuliah')->name('profil.kuliah');
Route::PATCH('/profil-kuliah/update/{study}', 'FrontendController@updateProfilKuliah')->name('updateProfil.kuliah');
//wirausaha
Route::get('/profil/{graduate}/wirausaha', 'FrontendController@ketWirausaha')->name('ket.wirausaha');
Route::PATCH('/profil/wirausaha/{graduate}', 'FrontendController@profilWirausaha')->name('profil.wirausaha');
Route::PATCH('/profil-wirausaha/update/{business}', 'FrontendController@updateProfilWirausaha')->name('updateProfil.wirausaha');
//bekerja
Route::get('/profil/{graduate}/bekerja', 'FrontendController@ketBekerja')->name('ket.bekerja');
Route::PATCH('/profil/bekerja/{graduate}', 'FrontendController@profilBekerja')->name('profil.bekerja');
Route::PATCH('/profil-bekerja/update/{work}', 'FrontendController@updateProfilBekerja')->name('updateProfil.bekerja');

//auth admin
Route::resource('/admin', 'AdminController');
Route::resource('/manajemen_alumni', 'ManajemenAlumniController');
Route::resource('/akun', 'AkunController');
Route::get('/akun/{user}/hapusgraduate', 'AkunController@hapusGraduate')->name('hapus.graduate');

//keterangan alumni kuliah
Route::get('/graduate/{graduate}/kuliah', 'KeteranganController@pilihKuliah')->name('pilih.kuliah');
Route::PATCH('/graduate/kuliah/{graduate}', 'KeteranganController@kuliah')->name('kuliah');
Route::get('/kuliah/{graduate}/edit', 'KeteranganController@editKuliah')->name('edit.kuliah');
Route::PATCH('/kuliah/update/{study}', 'KeteranganController@updateKuliah')->name('update.kuliah');

//keterangan alumni wirausaha
Route::get('/graduate/{graduate}/wirausaha', 'KeteranganController@pilihWirausaha')->name('pilih.wirausaha');
Route::PATCH('/graduate/wirausaha/{graduate}', 'KeteranganController@wirausaha')->name('wirausaha');
Route::get('/wirausaha/{graduate}/edit', 'KeteranganController@editWirausaha')->name('edit.wirausaha');
Route::PATCH('/wirausaha/update/{business}', 'KeteranganController@updateWirausaha')->name('update.wirausaha');

//keterangan alumni bekerja
Route::get('/graduate/{graduate}/bekerja', 'KeteranganController@pilihBekerja')->name('pilih.bekerja');
Route::PATCH('/graduate/bekerja/{graduate}', 'KeteranganController@bekerja')->name('bekerja');
Route::get('/bekerja/{graduate}/edit', 'KeteranganController@editBekerja')->name('edit.bekerja');
Route::PATCH('/bekerja/update/{work}', 'KeteranganController@updateBekerja')->name('update.bekerja');

Route::get('/Graduate/export_excel', 'ExportImportController@export_excel')->name('graduate.export');
Route::post('/Graduate/import_excel', 'ExportImportController@import_excel')->name('graduate.import');
Route::resource('/bursa_kerja', 'BursaKerjaController');
Route::resource('/category', 'CategoryController');
Route::resource('/mou', 'MouController');
//manajemen website
Route::get('/manajemen_website', 'WebsiteController@index')->name('manajemen.website');
Route::PATCH('/manajemen_website/update/', 'WebsiteController@update')->name('update.website');

});


// Route::get('/graduate/login', 'GraduateLoginController@showLoginForm')->name('graduate.loginform');
// Route::get('/graduate/register', 'GraduateLoginController@showRegisterForm')->name('graduate.registerform');
// Route::post('/graduate/login', 'GraduateLoginController@login')->name('graduate.login');
// Route::post('/graduate/register', 'GraduateLoginController@register')->name('graduate.register');
// Route::get('/graduate/profil', 'GraduateLoginController@index')->middleware('auth:graduate')->name('profil.alumni');
// Route::get('/graduate/logout', 'GraduateLoginController@logout')->name('graduate.logout');


// Route::PATCH('/profil/kuliah/{auth}', 'KeteranganController@kuliah')->name('submit.kuliah');

app/Http/Controllers/BursaKerjaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Loker;
use App\Category;
use App\Website;
use File;

class BursaKerjaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $website = Website::first();
        $lokers = Loker::orderBy('id', 'DESC')->get();
        $categories = Category::all();
        return view('backend.bursa_kerja.index', compact('website', 'lokers', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $destination = "public/brosurKerja";

        $brosur = $request->file('brosur');
        $extension = $brosur->getClientOriginalExtension(); 
        // RENAME THE UPLOAD WITH RANDOM NUMBER 
        $brosurName = rand(11111, 33333) . '.' . $extension; 
        // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY 
        $brosur->move($destination, $brosurName);

        $loker = new Loker;
        $loker->title = $request->title;
        $loker->deskripsi = $request->deskripsi;
        $loker->perusahaan = $request->perusahaan;
        $loker->category_id = $request->category_id;
        $loker->tgl_awal = $request->tgl_awal;
        $loker->tgl_akhir = $request->tgl_akhir;
        $loker->brosur = $brosurName;
        $loker->save(); 

        return redirect()->route('bursa_kerja.index')->with('success', 'Data telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $website = Website::first();
        $loker = Loker::find($id);
        return view('backend.bursa_kerja.show', compact('website', 'loker'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $website = Website::first();
        $loker = Loker::find($id);
        $categories = Category::all();
        // dd($loker);
        return view('backend.bursa_kerja.edit', compact('website', 'loker', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->brosur == null)
        {

            //$idUser = Auth::user()->id;
            //$tgl_wak = Carbon::now()->toDateTimeString('d-M-Y H:i');


            $loker = Loker::find($id);;
            $loker->title = $request->title;
            $loker->deskripsi = $request->deskripsi;
            $loker->perusahaan = $request->perusahaan;
            $loker->category_id = $request->category_id;
            $loker->tgl_awal = $request->tgl_awal;
            $loker->tgl_akhir = $request->tgl_akhir;
            $loker->push();

        }else
        {
            //$idUser = Auth::user()->id;
            //$tgl_wak = Carbon::now()->toDateTimeString('d-M-Y H:i');
            

            $destination = "public/brosurKerja";

            $brosur = $request->file('brosur');
            $extension = $brosur->getClientOriginalExtension(); 
            // RENAME THE UPLOAD WITH RANDOM NUMBER 
            $brosurName = rand(11111, 33333) . '.' . $extension; 
            // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY 
            $brosur->move($destination, $brosurName);

            // hapus file
            $gambar = Loker::where('id',$id)->first();
            File::delete('public/brosurKerja/'.$gambar->brosur);

            $loker = Loker::find($id);
            $loker->title = $request->title;
            $loker->deskripsi = $request->deskripsi;
            $loker->perusahaan = $request->perusahaan;
            $loker->category_id = $request->category_id;
            $loker->tgl_awal = $request->tgl_awal;
            $loker->tgl_akhir = $request->tgl_akhir;
            $loker->brosur = $brosurName;
            $loker->push(); 
        }

        return redirect()->route('bursa_kerja.index')->with('update', 'Data telah diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // hapus file
		$loker = Loker::where('id',$id)->first();
		File::delete('public/brosurKerja/'.$loker->brosur);
 
		// hapus data
        Loker::destroy($id);

        return redirect()->route('bursa_kerja.index')->with('delete', 'Data telah dihapus');
    }
}

resources/views/backend/bursa_kerja/edit.blade.php
@extends('backend.layouts.main')

@section('content')
<div class="page-wrapper mt-5 pt-4">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row align-items-center">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="page-title mb-0 p-0">Edit Bursa Kerja</h3>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Edit Bursa Kerja</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-md-6 col-4 align-self-center">
                <div class="text-end upgrade-btn">
                    <!-- Button trigger modal -->
                    <!-- <button type="button" class="btn btn-success d-md-inline-block text-white" data-toggle="modal" data-target="#tambahBursa">
                        Tambah
                    </button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="bg-info text-white card-header">
                       <strong>Data Bursa Kerja</strong> 
                    </div>
                    <div class="card-body">
                        <!-- <h4 class="card-title">Basic Table</h4>
                        <h6 class="card-subtitle">Add class <code>.table</code></h6> -->
                        <form method="post" action="{{ route('bursa_kerja.update', $loker->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="row form-body">
                                <div class="col-6">
                                    <div class="form-group">
                                        <label for="exampleInputNama">Title</label>
                                        <input type="text" name="title" value="{{ $loker->title }}" class="form-control" id="exampleInputNama" aria-describedby="emailHelp" placeholder="">
                                        <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputNama">Deskripsi</label>
                                        <textarea name="deskripsi" value="" class="form-control" id="exampleFormControlTextarea1" rows="4">{{ $loker->deskripsi }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputNama">Perusahaan</label>
                                        <input type="text" name="perusahaan" value="{{ $loker->perusahaan }}" class="form-control" id="exampleInputNama" aria-describedby="emailHelp" placeholder="">
                                        <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                                    </div>
                                </div>

                                <div class="col-6">
                                    
                                    <div class="form-group">
                                        <label>Brosur</label>
                                        <input type="file" name="brosur" value="{{ $loker->brosur }}" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputNama">Tanggal Awal</label>
                                        <input type="date" name="tgl_awal" value="{{ $loker->tgl_awal }}" class="form-control">
                                        <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputNama">Tanggal Akhir</label>
                                        <input type="date" name="tgl_akhir" value="{{ old('$loker->tgl_akhir') }}" class="form-control">
                                        <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Kategori</label>
                                        <select name="category_id" class="form-control">
                                            <option>--pilih kategori--</option>
                                            @foreach( $categories as $category )
                                                <option value="{{ $category->id }}">{{ $category->kategori }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                            </div>
                            <div class="form-actions">
                                <div class="text-right">
                                    <button type="submit" class="btn btn-info">Submit</button>
                                    <!-- <button type="reset" class="btn btn-dark">Reset</button> -->
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        © 2021 Bursa Kerja Khusus by <a href="https://smkn1tebas.sch.id/">smkn1tebas.sch.id</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>


@endsection

resources/views/backend/bursa_kerja/show.blade.php
@extends('backend.layouts.main')

@section('content')
<div class="page-wrapper mt-5 pt-4">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row align-items-center">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="page-title mb-0 p-0">Show Alumni</h3>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Show Alumni</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-md-6 col-4 align-self-center">
                <div class="text-end upgrade-btn">
                    <!-- Button trigger modal -->
                    <!-- <button type="button" class="btn btn-success d-md-inline-block text-white" data-toggle="modal" data-target="#tambahAlumni">
                        Tambah
                    </button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-5 col-xlg-4 col-md-6">
                <div class="card">
                    <div class="bg-info text-white card-header">
                       <strong>Data Bursa Kerja</strong> 
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-4">
                            <h6>Judul</h6>
                            </div>
                            <div class="col-sm-8">
                            <p><strong>:</strong> {{ $loker->title }}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                            <h6>Deskripsi</h6>
                            </div>
                            <div class="col-sm-8">
                            <p><strong>:</strong> {{ $loker->deskripsi }}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                            <h6>Perusahaan</h6>
                            </div>
                            <div class="col-sm-8">
                            <p><strong>:</strong> {{ $loker->perusahaan }}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                            <h6>Waktu</h6>
                            </div>
                            <div class="col-sm-8">
                            <p><strong>:</strong> {{ $loker->tgl_awal }} - {{ $loker->tgl_akhir }}</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                            <h6>Kategori</h6>
                            </div>
                            <div class="col-sm-8">
                            <p><strong>:</strong> {{ $loker->category->kategori }}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-lg-7 col-xlg-8 col-md-6">
                <div class="card">
                    <div class="bg-info text-white card-header">
                       <strong>Brosur Bursa Kerja</strong> 
                    </div>
                    <div class="card-body profile-card">
                        <center class="mt-4"> 
                        <img src="{{ asset('/brosurKerja/'.$loker->brosur) }}"
                        class="img-fluid" alt="Responsive image"/>
                        </center>
                    </div>

                </div>
                

            </div>
            <!-- Column -->
        </div>
        <!-- Row -->
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        © 2021 Bursa Kerja Khusus by <a href="https://smkn1tebas.sch.id/">smkn1tebas.sch.id</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>

@endsection