routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@beranda')->name('beranda');


Route::get('/all_loker', 'FrontendController@showAllLoker')->name('show.all'); 
Route::get('/cari_loker', 'FrontendController@cariLoker')->name('cari.loker');
Route::get('/show_loker/{loker}', 'FrontendController@showLoker')->name('show.loker');
Route::get('/kategori/{category}', 'FrontendController@categoryLoker')->name('category.loker');


Auth::routes();



Route::middleware('auth')->group(function(){

//auth frontend
Route::get('/home', 'HomeController@index')->name('home');
Route::delete('/message/hapus/{message}', 'HomeController@destroyPesan')->name('message.hapus');
Route::delete('/post/hapus/{post}', 'HomeController@destroyPost')->name('post.hapus');
Route::resource('/chatroom', 'ChatRoomController');
Route::post('/comment/{post}', 'CommentController@store')->name('comment.store');
Route::get('/comment/{post}', 'CommentController@index');

Route::PATCH('/profil/update/{id}', 'FrontendController@updateProfil')->name('updateProfil');

Route::PATCH('/kirim_pesan', 'FrontendController@kirimMessage')->name('kirim.message');
Route::get('/registerGraduate', 'FrontendController@registerGraduate')->name('registerGraduate');
Route::get('/pilihGraduate/{pilih}', 'FrontendController@pilihGraduate')->name('pilihGraduate');

//kuliah
Route::get('/profil/{graduate}/kuliah', 'FrontendController@ketKuliah')->name('ket.kuliah');
Route::PATCH('/profil/kuliah/{graduate}', 'FrontendController@profilKuliah')->name('profil.kuliah');
Route::PATCH('/profil-kuliah/update/{study}', 'FrontendController@updateProfilKuliah')->name('updateProfil.kuliah');
//wirausaha
Route::get('/profil/{graduate}/wirausaha', 'FrontendController@ketWirausaha')->name('ket.wirausaha');
Route::PATCH('/profil/wirausaha/{graduate}', 'FrontendController@profilWirausaha')->name('profil.wirausaha');
Route::PATCH('/profil-wirausaha/update/{business}', 'FrontendController@updateProfilWirausaha')->name('updateProfil.wirausaha');
//bekerja
Route::get('/profil/{graduate}/bekerja', 'FrontendController@ketBekerja')->name('ket.bekerja');
Route::PATCH('/profil/bekerja/{graduate}', 'FrontendController@profilBekerja')->name('profil.bekerja');
Route::PATCH('/profil-bekerja/update/{work}', 'FrontendController@updateProfilBekerja')->name('updateProfil.bekerja');

//auth admin
Route::resource('/admin', 'AdminController');
Route::resource('/manajemen_alumni', 'ManajemenAlumniController');
Route::resource('/akun', 'AkunController');
Route::get('/akun/{user}/hapusgraduate', 'AkunController@hapusGraduate')->name('hapus.graduate');

//keterangan alumni kuliah
Route::get('/graduate/{graduate}/kuliah', 'KeteranganController@pilihKuliah')->name('pilih.kuliah');
Route::PATCH('/graduate/kuliah/{graduate}', 'KeteranganController@kuliah')->name('kuliah');
Route::get('/kuliah/{graduate}/edit', 'KeteranganController@editKuliah')->name('edit.kuliah');
Route::PATCH('/kuliah/update/{study}', 'KeteranganController@updateKuliah')->name('update.kuliah');

//keterangan alumni wirausaha
Route::get('/graduate/{graduate}/wirausaha', 'KeteranganController@pilihWirausaha')->name('pilih.wirausaha');
Route::PATCH('/graduate/wirausaha/{graduate}', 'KeteranganController@wirausaha')->name('wirausaha');
Route::get('/wirausaha/{graduate}/edit', 'KeteranganController@editWirausaha')->name('edit.wirausaha');
Route::PATCH('/wirausaha/update/{business}', 'KeteranganController@updateWirausaha')->name('update.wirausaha');

//keterangan alumni bekerja
Route::get('/graduate/{graduate}/bekerja', 'KeteranganController@pilihBekerja')->name('pilih.bekerja');
Route::PATCH('/graduate/bekerja/{graduate}', 'KeteranganController@bekerja')->name('bekerja');
Route::get('/bekerja/{graduate}/edit', 'KeteranganController@editBekerja')->name('edit.bekerja');
Route::PATCH('/bekerja/update/{work}', 'KeteranganController@updateBekerja')->name('update.bekerja');

Route::get('/Graduate/export_excel', 'ExportImportController@export_excel')->name('graduate.export');
Route::post('/Graduate/import_excel', 'ExportImportController@import_excel')->name('graduate.import');
Route::resource('/bursa_kerja', 'BursaKerjaController');
Route::resource('/category', 'CategoryController');
Route::resource('/mou', 'MouController');
//manajemen website
Route::get('/manajemen_website', 'WebsiteController@index')->name('manajemen.website');
Route::PATCH('/manajemen_website/update/', 'WebsiteController@update')->name('update.website');

});


// Route::get('/graduate/login', 'GraduateLoginController@showLoginForm')->name('graduate.loginform');
// Route::get('/graduate/register', 'GraduateLoginController@showRegisterForm')->name('graduate.registerform');
// Route::post('/graduate/login', 'GraduateLoginController@login')->name('graduate.login');
// Route::post('/graduate/register', 'GraduateLoginController@register')->name('graduate.register');
// Route::get('/graduate/profil', 'GraduateLoginController@index')->middleware('auth:graduate')->name('profil.alumni');
// Route::get('/graduate/logout', 'GraduateLoginController@logout')->name('graduate.logout');


// Route::PATCH('/profil/kuliah/{auth}', 'KeteranganController@kuliah')->name('submit.kuliah');

app/Http/Controllers/ChatRoomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Comment;
use App\Website;
use App\Category;
use Auth;
use App\Graduate;
use File;

class ChatRoomController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
        $graduate = Graduate::where('user_id', $id)->first();
        $posts = Post::orderBy('id', 'DESC')->get();
        $comments = Comment::all();
        $website = Website::first();
        $categories = Category::all();
        return view('frontend.chatRoom.index', compact('graduate', 'posts', 'comments', 'website', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Auth::id();
        
        if($request->image == null){

            $post = new Post;
            $post->content = $request->content;
            $post->user_id = $id;
            $post->save();
        }else{

            $destination = "public/postImage";

            $image = $request->file('image');
            $extension = $image->getClientOriginalExtension(); 
            // RENAME THE UPLOAD WITH RANDOM NUMBER 
            $imageName = rand(11111, 33333) . '.' . $extension; 
            // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY 
            $image->move($destination, $imageName);
            
            $post = new Post;
            $post->content = $request->content;
            $post->image = $imageName;
            $post->user_id = $id;
            $post->save();
        }
         

        return redirect()->route('chatroom.index')->with('success', 'Data telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        $website = Website::first();
        $categories = Category::all();
        return view('frontend.chatRoom.show', compact('post', 'website', 'categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        if($post->image != null){
            File::delete('public/postImage'.$post->image);
        }else{
            
        }
        $post->delete();

        return redirect()->back()->with('delete', 'Postingan telah dihapus');
    }
}

resources/views/frontend/chatRoom/index.blade.php
@extends('frontend.layouts.main')

@section('content')
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <!-- <ol>
          <li><a href="/">Beranda</a></li>
          <li>Profil</li>
        </ol>
        <h5>Profil Alumni</h5> -->

      </div>
    </section><!-- End Breadcrumbs -->
<!-- <br>
    @if(Session::has('success'))
        <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ Session::get('success') }}</strong>
        </div>
    @endif
    @if(Session::has('update'))
        <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ Session::get('update') }}</strong>
        </div>
    @endif
    @if(Session::has('delete'))
        <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>{{ Session::get('delete') }}</strong>
        </div>
    @endif
<br> -->
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">

      <div class="container" data-aos="fade-up">

        <!-- <header class="section-header">
          <h2>Contact</h2>
          <p>Contact Us</p>
        </header> -->

        <div class="row gy-4">

          <div class="col-lg-4">

            <div class="row gy-4">
              <div class="col">
                <div class="info-box">
                  <center>
                  <img src="{{ asset('/profil/'.Auth::user()->profil) }}"
                            class="rounded-circle" width="140" />
                  
                  <h3>{{ auth()->user()->name }}</h3>
                  <p>NISN: {{ $graduate->nisn }}<br>
                  Angkatan: {{ $graduate->th_lulus }} <br>
                  @if($graduate->keterangan == "kuliah")
                    <p>Keterangan: Kuliah</p> 
                  @elseif($graduate->keterangan == "bekerja")
                    <p>Keterangan: Bekerja</p> 
                  @elseif($graduate->keterangan == "wirausaha")
                    <p>Keterangan: Wirausaha</p> 
                  @else
                    <p>Keterangan: Tidak ada</p> 
                  @endif
                  <!-- @if($graduate->keterangan == "kuliah")
                  <select name="forma" onchange="location = this.value;">
                    <option value="#">Kuliah</option>
                    <option value="{{ route('ket.bekerja', $graduate) }}">Bekerja</option>
                    <option value="{{ route('ket.wirausaha', $graduate) }}">Wirausaha</option>
                  </select>
                  @elseif($graduate->keterangan == "bekerja")
                  <select name="forma" onchange="location = this.value;">
                    <option value="#">Bekerja</option>
                    <option value="{{ route('ket.kuliah', $graduate) }}">Kuliah</option>
                    <option value="{{ route('ket.wirausaha', $graduate) }}">Wirausaha</option>
                  </select>
                  @elseif($graduate->keterangan == "wirausaha")
                  <select name="forma" onchange="location = this.value;">
                    <option value="#">Wirausaha</option>
                    <option value="{{ route('ket.kuliah', $graduate) }}">Kuliah</option>
                    <option value="{{ route('ket.bekerja', $graduate) }}">Bekerja</option>
                  </select>
                  @else
                  <select name="forma" onchange="location = this.value;">
                    <option value="">Tidak ada</option><hr>
                    <option value="{{ route('ket.kuliah', $graduate) }}">Kuliah</option>
                    <option value="{{ route('ket.bekerja', $graduate) }}">Bekerja</option>
                    <option value="{{ route('ket.wirausaha', $graduate) }}">Wirausaha</option>
                  </select>
                  @endif -->
                  </p>                
            
                  </center>
                </div>
              </div>
            </div>

          </div>

          <div class="col-lg-8">
            <form action="#" class="form-edit">
              <div class="row gy-4">

                <div class="col-md-12">
                  <img src="{{ asset('/assets_frontend\assets\img\imagePostingan.png') }}"
                            class="rounded img-fluid"/>
                </div>

                <div class="col-md-12">
                  <input type="text" name="name" class="form-control" placeholder="Posting Sesuatu"  data-bs-toggle="modal" data-bs-target="#exampleModal">
                </div>

                <!-- <div class="col-md-12 text-center">
                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Launch demo modal
                  </button>
                </div> -->

              </div>
            </form>

          </div>

        </div>
        
        <!-- <br>
        <div class="row">
          <div class="col-md-12">
            <div class="card border-info mb-3">
                <div class="card-header">
                </div>
                <div class="card-body text-info">
                  <div class="row">
                    <div class="col-lg-1 col-md-1 col-sm-1">
                      <a href="index.html">
                        <div class="align-items-center">
                          <img src="{{ asset('images/'.$website->header_logo) }}" width="60" alt="">
                          <p class="m-2"><strong>Budi</strong><small class="text-muted"> 07:30</small></p>
                        </div>
                      </a>
                    </div>
                    <div class="col-lg-11 col-md-11 col-sm-11">
                        <div class="m-2 search">
                            <div class="breadcrumbs-item breadcrumbs-form">
                              <form action="" method="GET">
                                <input type="text" name="cari" value="{{ old('cari') }}">
                                <button type="submit"><i class="bi bi-cursor-fill"></i></button>
                              </form>
                            </div>
                        </div>
                    </div>
                  </div>
                    
                </div>
                <div class="card-footer">
                  
                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Launch demo modal
                  </button>
                </div>
            </div>
          </div>
        </div> -->
        <br><hr><br>

        <div class="row">
          @foreach($posts as $post)
          
            <div class="col-md-2"><br><br>
              <div class="text-center">
                  <img src="{{ asset('/profil/'.$post->user->profil) }}" class="rounded-circle img-fluid" width="70" alt="">
                  <h5 class="pt-1 mb-0">{{ $post->user->name }}</h5> 
                  <p class="card-text"><small class="text-muted">{{ $post->created_at->diffForHumans()}}</small></p>
              </div>
            </div>
            <div class="col-md-10">
              <a href="{{ route('chatroom.show', $post->id) }}">
                <div class="card border-info mb-3">
                    <!-- <div class="card-header">
                    <img src="{{ asset('images/logobkk.png') }}"  class="rounded-circle" width="50" alt="">  
                    {{ $post->user->name }}
                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div> -->
                    <div class="card-footer text-info"><br>
                      <div class="justify-content-start"> 
                        @if(isset($post->image))
                          <div><img src="{{ asset('postImage/'.$post->image) }}" class="rounded img-fluid" width="450" alt=""></div><br>
                          <div><p class="card-text">{{ $post->content }}</p></div>
                        @else
                          <div><p class="card-text">{{ $post->content }}</p></div>
                        @endif
                      </div>
                    </div>
                    <div class="card-body">
                        <small class="text-muted"><i class="bi bi-people-fill"></i> {{ $post->comments->count() }} Komentar</small>
                        <br>
                        @if(isset($post->comments->last()->content))
                          <a href="{{ route('chatroom.show', $post->id) }}">
                            <div class="logo d-flex align-items-center">
                            <img src="{{ asset('/profil/'.$post->user->profil) }}" class="rounded-circle" width="25" alt="">
                            <h6 class="m-2">{{ $post->user->name }}</h6><small class="text-muted"> {{ $post->comments->last()->created_at->diffForHumans() }}</small>
                            </div>
                            <h6 class="m-2"><strong>{{ $post->comments->last()->content }}</strong></h6>
                          </a>
                        @else
                        
                        @endif
                        
                        <!-- <hr> -->

                        <!-- <div class="input-group mb-3">
                            <button class="btn btn-outline-secondary" type="submit" id="button-addon1">Send</button>
                            <input type="text" class="form-control" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                        </div> -->

                    </div>
                </div>
              </a>
            </div>
          
          @endforeach
        </div>

      </div>

    </section><!-- End Contact Section -->
  </main><!-- End #main -->
@endsection

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Posting</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form method="post" action="{{ route('chatroom.store') }}" enctype="multipart/form-data">
      @csrf
        <div class="modal-body">
          
            <div class="mb-3">
              <label for="recipient-name" class="col-form-label">Recipient:</label>
              <input type="file" name="image" class="form-control" id="recipient-name">
            </div>
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Message:</label>
              <textarea class="form-control" name="content"  rows="10" id="message-text"></textarea>
            </div>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Post</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/frontend/chatRoom/show.blade.php
@extends('frontend.layouts.main')

@section('content')

<main id="main">
<div id="app">
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <!-- <ol>
          <li><a href="/">Beranda</a></li>
          <li>Profil</li>
        </ol>
        <h5>Profil Alumni</h5> -->

      </div>
    </section><!-- End Breadcrumbs -->

    <section id="contact" class="contact">

    <div class="container" data-aos="fade-up">

    <div class="row">
        
        <div class="col-md-12">
            <div class="card border-info mb-3">
                <div class="card-header">
                
                </div>
                <div class="card-body text-info">
                <div class="justify-content-start">
                    <div class="text-center">
                        <img src="{{ asset('/profil/'.Auth::user()->profil) }}"  class="rounded-circle img-fluid" width="70" alt="">
                        <h5 class="pt-1 mb-0">{{ $post->user->name }}</h5> 
                        <p class="card-text"><small class="text-muted">{{ $post->created_at->diffForHumans()}}</small></p>
                    </div>
                    <hr>
                    <div class="text-center">
                    @if(isset($post->image))
                        <div><img src="{{ asset('postImage/'.$post->image) }}" class="rounded img-fluid" alt=""></div><br>
                        <div><p class="card-text">{{ $post->content }}</p></div>
                    @else
                        <div><p class="card-text">{{ $post->content }}</p></div>
                    @endif
                    </div>
                </div>
                    <!-- <h5 class="card-title">Info card title</h5>
                    <p class="card-text">{{ $post->content }}</p> -->
                </div>
                <div class="card-footer">
                    <small class="text-muted"><i class="bi bi-people-fill"></i> {{ $post->comments->count() }} Komentar</small>
                    <br>

                </div>
            </div>
        </div>
        <div class="col-md-12">
            <commentpost v-bind:post="{{ $post }}"></commentpost>
        </div>
        
    </div>

    </div>

    </section><!-- End Contact Section -->
</div>
</main><!-- End #main -->
@endsection